-- Check what status values exist in appointments
SELECT DISTINCT STATUS FROM DOCTORS_APPOINTMENTS;

-- Check appointments with prescriptions
SELECT 
    da.ID,
    da.APPOINTMENT_DATE,
    da.STATUS,
    CASE WHEN p.ID IS NOT NULL THEN 'HAS PRESCRIPTION' ELSE 'NO PRESCRIPTION' END as PRESCRIPTION_STATUS
FROM DOCTORS_APPOINTMENTS da
LEFT JOIN PRESCRIPTION p ON da.ID = p.APPOINTMENT_ID
ORDER BY da.ID DESC;

-- Update appointments to COMPLETED if they have prescriptions
UPDATE DOCTORS_APPOINTMENTS da
SET STATUS = 'COMPLETED'
WHERE EXISTS (
    SELECT 1 FROM PRESCRIPTION p WHERE p.APPOINTMENT_ID = da.ID
)
AND STATUS != 'COMPLETED';

COMMIT;

-- Verify
SELECT STATUS, COUNT(*) FROM DOCTORS_APPOINTMENTS GROUP BY STATUS;
