-- Add columns to MEDICAL_TECHNICIAN to store user info directly
ALTER TABLE MEDICAL_TECHNICIAN ADD NAME VARCHAR2(100);
ALTER TABLE MEDICAL_TECHNICIAN ADD EMAIL VARCHAR2(100);
ALTER TABLE MEDICAL_TECHNICIAN ADD PHONE VARCHAR2(20);

-- Make them NOT NULL after adding
ALTER TABLE MEDICAL_TECHNICIAN MODIFY NAME NOT NULL;
ALTER TABLE MEDICAL_TECHNICIAN MODIFY EMAIL NOT NULL;
ALTER TABLE MEDICAL_TECHNICIAN MODIFY PHONE NOT NULL;

-- Add unique constraint on email
ALTER TABLE MEDICAL_TECHNICIAN ADD CONSTRAINT uk_med_tech_email UNIQUE (EMAIL);
